# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0eprotocol.proto\"\xe1\x01\n\rMasterRequest\x12-\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x1c.MasterRequest.MasterCommand\x12\x11\n\tclient_id\x18\x02 \x01(\x05\x12\x30\n\x0einitialization\x18\x03 \x01(\x0b\x32\x16.InitializationRequestH\x00\x12\x17\n\x05\x66rame\x18\x04 \x01(\x0b\x32\x06.FrameH\x00\"8\n\rMasterCommand\x12\x12\n\x0eINITIALIZATION\x10\x00\x12\t\n\x05\x46RAME\x10\x01\x12\x08\n\x04NAME\x10\x02\x42\t\n\x07payload\"\'\n\x15InitializationRequest\x12\x0e\n\x06spaces\x18\x01 \x01(\x0c\"B\n\x05\x46rame\x12\x1b\n\x0bobservation\x18\x01 \x01(\x0b\x32\x06.Array\x12\x0e\n\x06reward\x18\x02 \x01(\x01\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"3\n\x05\x41rray\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\r\n\x05\x64type\x18\x03 \x01(\t\"0\n\x16InitializationResponse\x12\x16\n\x0e\x65nvironment_id\x18\x02 \x01(\x05\"\x16\n\x14\x43onfirmationResponse\"U\n\x0cNameResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04seed\x18\x02 \x01(\x05\x12\x16\n\x0eserver_version\x18\x03 \x01(\x05\x12\x11\n\tclient_id\x18\x04 \x01(\x05\"\x80\x01\n\rWorkerMessage\x12-\n\x07\x63ommand\x18\x01 \x01(\x0e\x32\x1c.WorkerMessage.WorkerCommand\x12\x0f\n\x07\x61\x63tions\x18\x02 \x03(\x05\"/\n\rWorkerCommand\x12\x08\n\x04STEP\x10\x00\x12\t\n\x05RESET\x10\x01\x12\t\n\x05\x43LOSE\x10\x02\x62\x06proto3')
)



_MASTERREQUEST_MASTERCOMMAND = _descriptor.EnumDescriptor(
  name='MasterCommand',
  full_name='MasterRequest.MasterCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INITIALIZATION', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRAME', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NAME', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=177,
  serialized_end=233,
)
_sym_db.RegisterEnumDescriptor(_MASTERREQUEST_MASTERCOMMAND)

_WORKERMESSAGE_WORKERCOMMAND = _descriptor.EnumDescriptor(
  name='WorkerCommand',
  full_name='WorkerMessage.WorkerCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STEP', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=651,
  serialized_end=698,
)
_sym_db.RegisterEnumDescriptor(_WORKERMESSAGE_WORKERCOMMAND)


_MASTERREQUEST = _descriptor.Descriptor(
  name='MasterRequest',
  full_name='MasterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='MasterRequest.command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='MasterRequest.client_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initialization', full_name='MasterRequest.initialization', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frame', full_name='MasterRequest.frame', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MASTERREQUEST_MASTERCOMMAND,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='MasterRequest.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=19,
  serialized_end=244,
)


_INITIALIZATIONREQUEST = _descriptor.Descriptor(
  name='InitializationRequest',
  full_name='InitializationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spaces', full_name='InitializationRequest.spaces', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=285,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='observation', full_name='Frame.observation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reward', full_name='Frame.reward', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='done', full_name='Frame.done', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=353,
)


_ARRAY = _descriptor.Descriptor(
  name='Array',
  full_name='Array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='Array.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='shape', full_name='Array.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dtype', full_name='Array.dtype', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=406,
)


_INITIALIZATIONRESPONSE = _descriptor.Descriptor(
  name='InitializationResponse',
  full_name='InitializationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='environment_id', full_name='InitializationResponse.environment_id', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=408,
  serialized_end=456,
)


_CONFIRMATIONRESPONSE = _descriptor.Descriptor(
  name='ConfirmationResponse',
  full_name='ConfirmationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=480,
)


_NAMERESPONSE = _descriptor.Descriptor(
  name='NameResponse',
  full_name='NameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NameResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seed', full_name='NameResponse.seed', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_version', full_name='NameResponse.server_version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='NameResponse.client_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=567,
)


_WORKERMESSAGE = _descriptor.Descriptor(
  name='WorkerMessage',
  full_name='WorkerMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='WorkerMessage.command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actions', full_name='WorkerMessage.actions', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _WORKERMESSAGE_WORKERCOMMAND,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=698,
)

_MASTERREQUEST.fields_by_name['command'].enum_type = _MASTERREQUEST_MASTERCOMMAND
_MASTERREQUEST.fields_by_name['initialization'].message_type = _INITIALIZATIONREQUEST
_MASTERREQUEST.fields_by_name['frame'].message_type = _FRAME
_MASTERREQUEST_MASTERCOMMAND.containing_type = _MASTERREQUEST
_MASTERREQUEST.oneofs_by_name['payload'].fields.append(
  _MASTERREQUEST.fields_by_name['initialization'])
_MASTERREQUEST.fields_by_name['initialization'].containing_oneof = _MASTERREQUEST.oneofs_by_name['payload']
_MASTERREQUEST.oneofs_by_name['payload'].fields.append(
  _MASTERREQUEST.fields_by_name['frame'])
_MASTERREQUEST.fields_by_name['frame'].containing_oneof = _MASTERREQUEST.oneofs_by_name['payload']
_FRAME.fields_by_name['observation'].message_type = _ARRAY
_WORKERMESSAGE.fields_by_name['command'].enum_type = _WORKERMESSAGE_WORKERCOMMAND
_WORKERMESSAGE_WORKERCOMMAND.containing_type = _WORKERMESSAGE
DESCRIPTOR.message_types_by_name['MasterRequest'] = _MASTERREQUEST
DESCRIPTOR.message_types_by_name['InitializationRequest'] = _INITIALIZATIONREQUEST
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
DESCRIPTOR.message_types_by_name['Array'] = _ARRAY
DESCRIPTOR.message_types_by_name['InitializationResponse'] = _INITIALIZATIONRESPONSE
DESCRIPTOR.message_types_by_name['ConfirmationResponse'] = _CONFIRMATIONRESPONSE
DESCRIPTOR.message_types_by_name['NameResponse'] = _NAMERESPONSE
DESCRIPTOR.message_types_by_name['WorkerMessage'] = _WORKERMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MasterRequest = _reflection.GeneratedProtocolMessageType('MasterRequest', (_message.Message,), dict(
  DESCRIPTOR = _MASTERREQUEST,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:MasterRequest)
  ))
_sym_db.RegisterMessage(MasterRequest)

InitializationRequest = _reflection.GeneratedProtocolMessageType('InitializationRequest', (_message.Message,), dict(
  DESCRIPTOR = _INITIALIZATIONREQUEST,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:InitializationRequest)
  ))
_sym_db.RegisterMessage(InitializationRequest)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), dict(
  DESCRIPTOR = _FRAME,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:Frame)
  ))
_sym_db.RegisterMessage(Frame)

Array = _reflection.GeneratedProtocolMessageType('Array', (_message.Message,), dict(
  DESCRIPTOR = _ARRAY,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:Array)
  ))
_sym_db.RegisterMessage(Array)

InitializationResponse = _reflection.GeneratedProtocolMessageType('InitializationResponse', (_message.Message,), dict(
  DESCRIPTOR = _INITIALIZATIONRESPONSE,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:InitializationResponse)
  ))
_sym_db.RegisterMessage(InitializationResponse)

ConfirmationResponse = _reflection.GeneratedProtocolMessageType('ConfirmationResponse', (_message.Message,), dict(
  DESCRIPTOR = _CONFIRMATIONRESPONSE,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:ConfirmationResponse)
  ))
_sym_db.RegisterMessage(ConfirmationResponse)

NameResponse = _reflection.GeneratedProtocolMessageType('NameResponse', (_message.Message,), dict(
  DESCRIPTOR = _NAMERESPONSE,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:NameResponse)
  ))
_sym_db.RegisterMessage(NameResponse)

WorkerMessage = _reflection.GeneratedProtocolMessageType('WorkerMessage', (_message.Message,), dict(
  DESCRIPTOR = _WORKERMESSAGE,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:WorkerMessage)
  ))
_sym_db.RegisterMessage(WorkerMessage)


# @@protoc_insertion_point(module_scope)
